apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-default-certificate
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: enable_cert_manager
              operator: In
              values: ['true']
            - key: cert_manager_use_default_cert
              operator: In
              values: ['true']
  template:
    metadata:
      name: cert-manager-default-certificate
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: default
      sources:
      - repoURL: '{{.metadata.annotations.applications_repo_url}}'
        targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
        ref: values
      - path: 'stackit/cert-manager-webhook-secret'
        repoURL: 'https://github.com/valiton-k8s-blueprints/charts.git'
        targetRevision: 'feature/stackit'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/values.yaml
            - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
          values: |
            certificate:
              dnsNames: {{.metadata.annotations.cert_manager_default_cert_domain_list}}
      destination:
        namespace: cert-manager
        name: '{{.name}}'
      syncPolicy:
        automated:
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        retry:
          backoff:
            duration: 1m
          limit: 60
