apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-crds
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: enable_cert_manager
              operator: In
              values: ['true']
  template:
    metadata:
      name: cert_manager-crds
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: default
      sources:
      - repoURL: '{{.metadata.annotations.applications_repo_url}}'
        targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
        ref: values
      - path: 'stackit/cert_manager-crds'
        repoURL: 'https://github.com/valiton-k8s-blueprints/charts.git'
        targetRevision: 'feature/stackit'
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          allowEmpty: true
        retry:
          backoff:
            duration: 1m
          limit: 60
