apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-admission-webhook-certificate
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: enable_cert_manager
              operator: In
              values: ['true']
            - key: enable_ingress_nginx
              operator: In
              values: ['true']
  template:
    metadata:
      name: nginx-admission-webhook-certificate
    spec:
      project: default
      sources:
      - repoURL: '{{.metadata.annotations.applications_repo_url}}'
        targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
        ref: values
      - path: 'stackit/nginx-admission-webhook-certificate'
        repoURL: 'https://github.com/valiton-k8s-blueprints/charts.git'
        targetRevision: 'feature/stackit'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - $values/{{.metadata.annotations.applications_repo_path}}/config/nginx-admission-webhook-certificate/values.yaml
            - $values/{{.metadata.annotations.applications_repo_path}}/config/nginx-admission-webhook-certificate/{{.metadata.labels.environment}}.yaml
      destination:
        namespace: ingress-nginx
        name: '{{.name}}'
      syncPolicy:
        automated:
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        retry:
          backoff:
            duration: 1m
          limit: 60
