apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: cert-manager-issuers
                addonChartVersion: main
                addonChartRepository: https://github.com/valiton-k8s-blueprints/charts.git
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: main
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: main
  template:
    metadata:
      name: '{{.values.addonChart}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - path: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
            values: |
              clusterIssuer:
                default:
                  name: {{.metadata.annotations.cert_manager_default_cert_dns01_issuer_name}}
              acme:
                registrationEmail: {{.metadata.annotations.cert_manager_acme_registration_email}}
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
