---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: designate-certmanager-webhook
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: designate-certmanager-webhook
                addonChartVersion: v0.1.2
                addonChartRepository: ghcr.io/stackitcloud/charts
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: v0.1.2
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: v0.1.2
  template:
    metadata:
      name: '{{.values.addonChart}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
      destination:
        namespace: cert-manager
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
