---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                # anything not staging or prod use this version
                addonVersion: cluster-autoscaler-9.58.0-bp.0
                addonRepository: https://github.com/valiton-k8s-blueprints/kustomize.git
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonVersion: cluster-autoscaler-9.58.0-bp.0
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonVersion: cluster-autoscaler-9.58.0-bp.0
  template:
    metadata:
      name: cluster-autoscaler
    spec:
      project: default
      source:
        repoURL: '{{.values.addonRepository}}'
        path: 'cluster-autoscaler'
        targetRevision: '{{.values.addonVersion}}'
      destination:
        namespace: kube-system
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
