---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openstack-cloud-controller-manager
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: openstack-cloud-controller-manager
                addonChartRepository: https://kubernetes.github.io/cloud-provider-openstack
                addonChartVersion: 2.32.0
              selector:
                matchExpressions:
                  - key: enable_cloud_controller_manager
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 2.32.0
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: 2.32.0
  template:
    metadata:
      name: '{{.values.addonChart}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.applications_repo_path}}/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
            values: |
              cluster:
                name: {{.name}}
      destination:
        namespace: kube-system
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
