---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: argo-cd
                # anything not staging or prod use this version
                addonChartVersion: 8.0.9
                addonChartRepositoryNamespace: argocd
                addonChartRepository: https://argoproj.github.io/argo-helm
              selector:
                matchExpressions:
                  - key: enable_argocd
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 8.0.9
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: 8.0.9
  template:
    metadata:
      name: '{{.values.addonChart}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/config/argocd/values.yaml
              - $values/config/argocd/{{.metadata.labels.environment}}.yaml
              - $values/config/argocd/{{.metadata.labels.cloud_provider}}.yaml
            values: |
              {{.metadata.annotations.argocd_cloud_provider_values | default ""}}
      destination:
        namespace: '{{.values.addonChartRepositoryNamespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
