---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: ingress-nginx
                # anything not staging or prod use this version
                addonChartVersion: 4.12.1
                addonChartRepository: https://kubernetes.github.io/ingress-nginx
              selector:
                matchExpressions:
                  - key: enable_ingress_nginx
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 4.12.1
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: 4.12.1
  template:
    metadata:
      name: '{{.values.addonChart}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/config/{{.values.addonChart}}/values.yaml
              - $values/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
              - $values/config/{{.values.addonChart}}/{{.metadata.labels.cloud_provider}}.yaml
            values: |
              {{.metadata.annotations.ingress_nginx_cloud_provider_values | default ""}}
      destination:
        namespace: '{{.metadata.annotations.ingress_nginx_namespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
