---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: metrics-server
                addonChartNamespace: kube-system
                # anything not staging or prod use this version
                addonChartVersion: 3.12.0
                addonChartRepository: https://kubernetes-sigs.github.io/metrics-server
              selector:
                matchExpressions:
                  - key: enable_metrics_server
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 3.12.0
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: 3.12.0
  template:
    metadata:
      name: '{{.values.addonChart}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/config/metrics-server/values.yaml
              - $values/config/metrics-server/{{.metadata.labels.environment}}.yaml
              - $values/config/metrics-server/{{.metadata.labels.cloud_provider}}.yaml
            values: |
              {{.metadata.annotations.metrics_server_cloud_provider_values | default ""}}
      destination:
        namespace: '{{.values.addonChartNamespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
