---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-designate-webhook
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChartVersion: v0.1.2
                addonChartRepository: ghcr.io/stackitcloud/charts
              selector:
                matchExpressions:
                  - key: enable_cert_manager_designate_webhook
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: v0.1.2
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                addonChartVersion: v0.1.2
  template:
    metadata:
      name: 'cert-manager-designate-webhook'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - path: designate-certmanager-webhook
          chart: designate-certmanager-webhook
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: 'cert-manager-designate-webhook'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/config/cert-manager-designate-webhook/values.yaml
              - $values/config/cert-manager-designate-webhook/{{.metadata.labels.environment}}.yaml
            values: |
              credentialsSecret: {{.metadata.annotations.cert_manager_designate_webhook_secret_name}}
              certManager:
                namespace: {{.metadata.annotations.cert_manager_namespace}}
                serviceAccountName: {{.metadata.annotations.cert_manager_service_account_name}}
      destination:
        namespace: '{{.metadata.annotations.cert_manager_namespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
