---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openstack-cinder-csi
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: openstack-cinder-csi
                addonChartRepository: https://kubernetes.github.io/cloud-provider-openstack
              selector:
                matchExpressions:
                  - key: enable_cinder_csi_plugin
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
          - clusters:
              selector:
                matchLabels:
                  environment: production
  template:
    metadata:
      name: '{{.values.addonChart}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '2.32.0'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/config/{{.values.addonChart}}/values.yaml
              - $values/config/{{.values.addonChart}}/{{.metadata.labels.environment}}.yaml
            values: |
              storageClass:
                enabled: false
                custom: |-
                  ---
                  apiVersion: storage.k8s.io/v1
                  kind: StorageClass
                  metadata:
                    name: 'csi-cinder-sc-delete'
                    annotations:
                      storageclass.kubernetes.io/is-default-class: "true"
                  provisioner: cinder.csi.openstack.org
                  reclaimPolicy: Delete
                  allowVolumeExpansion: true
                  parameters:
                    type: '{{.metadata.annotations.cinder_csi_plugin_volume_type}}'
              clusterID: '{{.metadata.annotations.cluster_name}}'
              secret:
                enabled: true
                name: "cinder-csi-plugin-secret"
              csi:
                plugin:
                  volumes:
                    - name: cacert
                      hostPath:
                        path: /etc/ssl/certs/ca-certificates
      destination:
        namespace: '{{.metadata.annotations.cinder_csi_plugin_namespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
