apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-openstack-credentials
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: enable_external_secrets
              operator: In
              values: ['true']
  template:
    metadata:
      name: external-secrets-openstack-credentials
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.applications_repo_url}}'
          targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
          ref: values
        - repoURL: 'https://github.com/valiton-k8s-blueprints/charts.git'
          path: 'bws/external-secrets-openstack-credentials'
          targetRevision: 'main'
          helm:
            releaseName: external-secrets-openstack-credentials
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/config/bws/external-secrets-openstack-credentials/values.yaml
              - $values/config/bws/external-secrets-openstack-credentials/{{.metadata.labels.environment}}.yaml
            values: |
              {{.metadata.annotations.external_secrets_openstack_credentials_cloud_provider_values | default ""}}
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
