acme:
  url: https://acme-v02.api.letsencrypt.org/directory
  http01:
    enabled: false
  dns01:
    enabled: true
    solver:
      webhook:
        groupName: acme.stackit.de
        solverName: stackit
        config:
          authTokenSecretNamespace: cert-manager
