apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-crs
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: enable_external_secrets
              operator: In
              values: ['true']
  template:
    metadata:
      name: external-secrets-crs
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: default
      sources:
      - repoURL: '{{.metadata.annotations.applications_repo_url}}'
        targetRevision: '{{.metadata.annotations.applications_repo_revision}}'
        ref: values
      - path: 'stackit/external-secrets-crs'
        repoURL: 'https://github.com/valiton-k8s-blueprints/charts.git'
        targetRevision: 'feature/external_secrets_0_18_x'
        helm:
          values: |
            stackit:
              sm_user: {{.metadata.annotations.stackit_sm_user}}
              sm_secret_name: {{.metadata.annotations.stackit_sm_secret_name}}
              sm_secret_namespace: {{.metadata.annotations.stackit_sm_secret_namespace}}
              sm_secret_instance_id: {{.metadata.annotations.stackit_sm_instance_id}}
      destination:
        name: '{{.name}}'
      syncPolicy:
        automated:
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        retry:
          backoff:
            duration: 1m
          limit: 60
