controller:
  admissionWebhooks:
    enabled: true
    patch:
      enabled: false
  ingressClassResource:
    name: nginx
    default: true
  config:
    use-proxy-protocol: "true"
  service:
    externalTrafficPolicy: "Local"
certManager:
  enabled: true
