controller:
  ingressClassResource:
    name: nginx
    default: true
  config:
    use-proxy-protocol: "true"
  service:
    externalTrafficPolicy: "Local"
  admissionWebhooks:
    timeoutSeconds: 60
