controller:
  annotations:
    yawol.stackit.cloud/tcpProxyProtocol: "true"
  service:
    externalTrafficPolicy: "Local"
  admissionWebhooks:
    enabled: true
    secretName: ingress-nginx-admission
    certManager:
      enabled: true  # << this disables createSecretJob
    patch:
      enabled: true  # << still needed to patch the caBundle
  ingressClassResource:
    name: nginx
    default: true


